package(default_visibility = ["//visibility:public"])

config_setting(
    name = "enable_wave_tracing",
    values = {
        "define": "WAVE_ON=1",
    },
    visibility = ["//visibility:public"],
)